### ISSUE TITLE
Docker compose : kafka and crawler containers restarting forever

### ISSUE THREAD

**Issue by llermaly** [istresearch/scrapy-cluster#206] opened 2018-11-19 23:04 UTC
Hello,  I'm trying to make quickstart work but after pulling containers wurstmeister/kafka and scrapy-cluster:crawler containers keep status restarting.

From error logs : 

kafka:
```
 ERROR: No listener or advertised hostname configuration provided in environment.
2018-11-19T22:46:22.884011669Z        Please define KAFKA_LISTENERS / (deprecated) KAFKA_ADVERTISED_HOST_NAME
```

crawler:
```
ERROR: Unable to connect to Kafka in Pipeline, raising exit flag.
2018-11-19T22:47:41.710214263Z Unhandled error in Deferred:
```
Testing pass OK on the other containers but after passing start throwing kafka related errors.

Thanks

**Comment by llermaly** [comment] 2018-11-20 02:57
Solved :) 

Step 1 : 

Modify docker-compose.yml file inside scrapy-cluster folder, add some enviroment variables : 

```
environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ADVERTISED_PORT: "9092"
```
KAFKA_ADVERTISED_HOST_NAME and KAFKA_ADVERTISED_PORT were missing

run docker-compose up --force-recreate -d

now tests are passing

**Comment by llermaly** [comment] 2018-11-20 10:52
Solved :) 

Go to localsettings.py in rest cluster and change FLASK port

Not sure if this could cause future problems,  hope not.

regards

**Comment by llermaly** [comment] 2018-11-20 11:07
After that I tried rest commands , all OK until feed, got this error : 

```
2018-11-20 11:04:03,946 [rest-service] INFO: 'feed' endpoint called
2018-11-20 11:04:34,064 [rest-service] ERROR: Failed to send message to Kafka
2018-11-20 11:04:34,064 [rest-service] ERROR: Lost connection to Kafka
2018-11-20 11:04:34,072 [rest-service] WARNING: Unable to write request to Kafka, not connected
127.0.0.1 - - [20/Nov/2018 11:04:34] "POST /feed HTTP/1.1" 500 -
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "rest_service.py", line 256, in _consumer_loop
    self._process_messages()
  File "rest_service.py", line 262, in _process_messages
    for message in self.consumer:
  File "/usr/local/lib/python2.7/site-packages/kafka/vendor/six.py", line 561, in next
    return type(self).__next__(self)
  File "/usr/local/lib/python2.7/site-packages/kafka/consumer/group.py", line 964, in __next__
    return next(self._iterator)
  File "/usr/local/lib/python2.7/site-packages/kafka/consumer/group.py", line 899, in _message_generator
    self._update_fetch_positions(partitions)
  File "/usr/local/lib/python2.7/site-packages/kafka/consumer/group.py", line 882, in _update_fetch_positions
    self._fetcher.update_fetch_positions(partitions)
  File "/usr/local/lib/python2.7/site-packages/kafka/consumer/fetcher.py", line 175, in update_fetch_positions
    self._reset_offset(tp)
  File "/usr/local/lib/python2.7/site-packages/kafka/consumer/fetcher.py", line 201, in _reset_offset
    offset = self._offset(partition, timestamp)
  File "/usr/local/lib/python2.7/site-packages/kafka/consumer/fetcher.py", line 234, in _offset
    self._client.poll(future=refresh_future, sleep=True)
  File "/usr/local/lib/python2.7/site-packages/kafka/client_async.py", line 501, in poll
    metadata_timeout_ms = self._maybe_refresh_metadata()
  File "/usr/local/lib/python2.7/site-packages/kafka/client_async.py", line 718, in _maybe_refresh_metadata
    node_id = self.least_loaded_node()
  File "/usr/local/lib/python2.7/site-packages/kafka/client_async.py", line 670, in least_loaded_node
    self._bootstrap(collect_hosts(self.config['bootstrap_servers']))
  File "/usr/local/lib/python2.7/site-packages/kafka/client_async.py", line 236, in _bootstrap
    bootstrap.connect()
  File "/usr/local/lib/python2.7/site-packages/kafka/conn.py", line 275, in connect
    self.config['state_change_callback'](self)
  File "/usr/local/lib/python2.7/site-packages/kafka/client_async.py", line 280, in _conn_state_change
    self._selector.register(conn._sock, selectors.EVENT_WRITE)
  File "/usr/local/lib/python2.7/site-packages/kafka/vendor/selectors34.py", line 436, in register
    self._epoll.register(key.fd, epoll_events)
ValueError: I/O operation on closed epoll fd

2018-11-20 11:04:34,284 [rest-service] INFO: Connected successfully to Kafka
2018-11-20 11:04:34,293 [rest-service] INFO: Connected successfully to Kafka
Exception in thread Thread-17:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "rest_service.py", line 256, in _consumer_loop
    self._process_messages()
  File "rest_service.py", line 262, in _process_messages
    for message in self.consumer:
  File "/usr/local/lib/python2.7/site-packages/kafka/vendor/six.py", line 561, in next
    return type(self).__next__(self)
  File "/usr/local/lib/python2.7/site-packages/kafka/consumer/group.py", line 964, in __next__
    return next(self._iterator)
ValueError: generator already executing
```

Will be posting if I found something

**Comment by madisonb** [comment] 2018-11-20 14:43
I am not sure what docker-compose file you were using, but https://github.com/istresearch/scrapy-cluster/blob/master/docker-compose.yml#L49 has the `KAFKA_ADVERTISED_HOST_NAME` already there.

As to your second comment, it looks like you already have something running on that port or there is some other issue. A port conflict within the container shouldn't be happening as there is only one process running.

This project is mostly maintained on the `dev` branch, so if you can give me steps to reproduce the above on that branch I would be happy to look into it.

Otherwise, I am closing this for now.

**Closed by madisonb** 2018-11-20 14:43 UTC

**Comment by llermaly** [comment] 2018-11-20 15:07
I downloaded and unzipped from here as tutorial says : 

https://github.com/istresearch/scrapy-cluster/releases 
https://github.com/istresearch/scrapy-cluster/archive/v1.2.1.zip

And KAFKA_ADVERTISED_HOST_NAME is not there 

regarding second issue I'm not running anything before launching rest in docker, so probably im using the wrong docker containers.

Thanks!

**Comment by madisonb** [comment] 2018-11-20 15:20
Ah gotcha, in looking at the diff between master and that release it indeed has the hostname fix https://github.com/istresearch/scrapy-cluster/compare/v1.2.1...master but I didn't deem it worthy of a release. Feel free to move over to the Gitter chat for more informal questions not directly related to bugs.
