### ISSUE TITLE
ERROR: Could not reach out to get public ip

### ISSUE THREAD

**Issue by mohit0749** [istresearch/scrapy-cluster#169] opened 2018-01-25 07:08 UTC
i am getting this error when crawler run in the background.

**Comment by madisonb** [comment] 2018-01-25 15:03
Your crawler cannot crawl if it cannot reach out to grab its public ip, or access the open internet. If you could provide more info I can try to help, but this seems definitely like a configuration issue.

Going to close this unless further feedback is supplied

**Comment by mohit0749** [comment] 2018-01-29 03:52
Since crawler is running on remote server, there would be no internet problem.
And 
here is settings.py 
```
from __future__ import absolute_import
# This file houses all default settings for the Crawler
# to override please use a custom localsettings.py file

# Scrapy Cluster Settings
# ~~~~~~~~~~~~~~~~~~~~~~~

# Specify the host and port to use when connecting to Redis.
REDIS_HOST = 'localhost'
REDIS_PORT = '6379'
REDIS_DB = 0

# Kafka server information
KAFKA_HOSTS = ['localhost:9092']
KAFKA_TOPIC_PREFIX = 'demo'
KAFKA_APPID_TOPICS = False
# base64 encode the html body to avoid json dump errors due to malformed text
KAFKA_BASE_64_ENCODE = False
KAFKA_PRODUCER_BATCH_LINGER_MS = 25  # 25 ms before flush
KAFKA_PRODUCER_BUFFER_BYTES = 4 * 1024 * 1024  # 4MB before blocking

ZOOKEEPER_ASSIGN_PATH = '/scrapy-cluster/crawler/'
ZOOKEEPER_ID = 'all'
ZOOKEEPER_HOSTS = 'localhost:2181'

PUBLIC_IP_URL = 'http://ip.42.pl/raw'
IP_ADDR_REGEX = '(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})'

# Don't cleanup redis queues, allows to pause/resume crawls.
SCHEDULER_PERSIST = True

# seconds to wait between seeing new queues, cannot be faster than spider_idle time of 5
SCHEDULER_QUEUE_REFRESH = 10

# throttled queue defaults per domain, x hits in a y second window
QUEUE_HITS = 10
QUEUE_WINDOW = 60

# we want the queue to produce a consistent pop flow
QUEUE_MODERATED = True

# how long we want the duplicate timeout queues to stick around in seconds
DUPEFILTER_TIMEOUT = 600

# how often to refresh the ip address of the scheduler
SCHEDULER_IP_REFRESH = 60

# whether to add depth >= 1 blacklisted domain requests back to the queue
SCHEDULER_BACKLOG_BLACKLIST = True

'''
----------------------------------------
The below parameters configure how spiders throttle themselves across the cluster
All throttling is based on the TLD of the page you are requesting, plus any of the
following parameters:

Type: You have different spider types and want to limit how often a given type of
spider hits a domain

IP: Your crawlers are spread across different IP's, and you want each IP crawler clump
to throttle themselves for a given domain

Combinations for any given Top Level Domain:
None - all spider types and all crawler ips throttle themselves from one tld queue
Type only - all spiders throttle themselves based off of their own type-based tld queue,
    regardless of crawler ip address
IP only - all spiders throttle themselves based off of their public ip address, regardless
    of spider type
Type and IP - every spider's throttle queue is determined by the spider type AND the
    ip address, allowing the most fined grained control over the throttling mechanism
'''
# add Spider type to throttle mechanism
SCHEDULER_TYPE_ENABLED = True

# add ip address to throttle mechanism
SCHEDULER_IP_ENABLED = True
'''
----------------------------------------
'''

# how many times to retry getting an item from the queue before the spider is considered idle
SCHEUDLER_ITEM_RETRIES = 3

# how long to keep around stagnant domain queues
SCHEDULER_QUEUE_TIMEOUT = 3600

# log setup scrapy cluster crawler
SC_LOGGER_NAME = 'sc-crawler'
SC_LOG_DIR = 'logs'
SC_LOG_FILE = 'sc_crawler.log'
SC_LOG_MAX_BYTES = 10 * 1024 * 1024
SC_LOG_BACKUPS = 5
SC_LOG_STDOUT = True
SC_LOG_JSON = False
SC_LOG_LEVEL = 'INFO'


# stats setup
STATS_STATUS_CODES = True
STATS_RESPONSE_CODES = [xx for xx in range(200,600)]
STATS_CYCLE = 5
# from time variables in scutils.stats_collector class
STATS_TIMES = [
    'SECONDS_15_MINUTE',
    'SECONDS_1_HOUR',
    'SECONDS_6_HOUR',
    'SECONDS_12_HOUR',
    'SECONDS_1_DAY',
    'SECONDS_1_WEEK',
]

# Scrapy Settings
# ~~~~~~~~~~~~~~~
# Scrapy settings for distributed_crawling project
#
BOT_NAME = 'drupalfit.com'

SPIDER_MODULES = ['crawling.spiders']
NEWSPIDER_MODULE = 'crawling.spiders'

# Enables scheduling storing requests queue in redis.
SCHEDULER = "crawling.distributed_scheduler.DistributedScheduler"



# Store scraped item in redis for post-processing.
ITEM_PIPELINES = {
    'crawling.pipelines.CouchdbPipeline':200,
#    'crawling.pipelines.KafkaPipeline': 100,
    'crawling.pipelines.LoggingBeforePipeline': 1,
}

SPIDER_MIDDLEWARES = {
    # disable built-in DepthMiddleware, since we do our own
    # depth management per crawl request
    'scrapy.spidermiddlewares.depth.DepthMiddleware': None,
    'crawling.meta_passthrough_middleware.MetaPassthroughMiddleware': 100,
    'crawling.redis_stats_middleware.RedisStatsMiddleware': 101
}

DOWNLOADER_MIDDLEWARES = {
    # Handle timeout retries with the redis scheduler and logger
    'scrapy.downloadermiddlewares.retry.RetryMiddleware': None,
    'crawling.redis_retry_middleware.RedisRetryMiddleware': 510,
    # exceptions processed in reverse order
    'crawling.log_retry_middleware.LogRetryMiddleware': 520,
    # custom cookies to not persist across crawl requests
    'scrapy.downloadermiddlewares.cookies.CookiesMiddleware': None,
    'crawling.custom_cookies.CustomCookiesMiddleware': 700,
}

# Disable the built in logging in production
LOG_ENABLED = False

# Allow all return codes
HTTPERROR_ALLOW_ALL = True

RETRY_TIMES = 3

DOWNLOAD_TIMEOUT = 10

# Avoid in-memory DNS cache. See Advanced topics of docs for info
DNSCACHE_ENABLED = True

# Local Overrides
# ~~~~~~~~~~~~~~~

try:
    from .localsettings import *
except ImportError:
    pass

```







 and localsettings.py
```
HTTPERROR_ALLOW_ALL = True
REDIRECT_ENABLED = False
USER_AGENT = "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"

# how often to refresh the ip address of the scheduler
SCHEDULER_IP_REFRESH = 300

# log setup scrapy cluster crawler
def log_dir():
    import os
    return os.path.join(os.path.expanduser('~'),'drupal-fit','logs')

SC_LOGGER_NAME = 'sc-crawler'
SC_LOG_DIR = log_dir()
SC_LOG_FILE = 'cluster.log'
SC_LOG_MAX_BYTES = 10 * 1024 * 1024
SC_LOG_BACKUPS = 5
SC_LOG_STDOUT = False
SC_LOG_JSON = False
```

**Comment by madisonb** [comment] 2018-01-29 15:00
So I am unsure of your setup, but just because the crawler is on a remote server does not mean you can reach out to the public web over port 80 or port 443. SSH uses port 22, so you at least know that is working, and I assume you pulled the containers or git repo from the web, so lets assume that works as well.

You can try the following:
1) Can you run `curl http://ip.42.pl/raw` from the command line?
2) (if using a container) If you `exec /bin/bash` into the container, can you do `apt-get update`, install curl, and run `curl http://ip.42.pl/raw` from the command line inside the container?
3) Do you have any special networking or bridge setups for your container?
4) What about iptables? Do you have any special configs there?
5) Turn `LOG_ENABLED = False` to True to see the scrapy logger, there may be something there

Overall, if you can replicate it on your machine vs on your remote server, that would help in diagnosing the issue.

**Comment by mohit0749** [comment] 2018-01-30 07:08
Yeah, I am using git repo.

`curl http://ip.42.pl/raw` working fine from the command line and I am not using container setup.

`ERROR: Could not reach out to get public IP` occurs very often but I noticed that when it occurs, crawler stops crawling.
Maybe this errors occurring becoz of very frequent IP refresh rate.

**Comment by madisonb** [comment] 2018-01-30 14:57
I am not sure I have seen this before, what version of scrapy cluster are you running? How many crawls are you trying to execute on a machine? How big is the machine (CPU/RAM/IO/etc). What operating system are you running? 

To me this seems like a custom setup problem - if you can reproduce it locally with this repo please provide further instructions so I can replicate it, otherwise it is hard to help assist.

**Comment by mohit0749** [comment] 2018-02-05 12:45
scrapy cluster version 1.2 and only one crawl was running with 3 crawlers on different machines.
Machine configuration is 2Ghz(1core)/2GB Ram.
OS is Ubuntu 14.04.

Even with the main repo without modifying anything except the pipeline code, the problem is occurring.

**Comment by madisonb** [comment] 2018-02-05 15:23
Please provide the exact steps to reproduce it locally on the Vagrant machine provided by the project, or using the containers running on your local machine, not in the cloud. That way I am working with the same machine you are.

**Comment by madisonb** [comment] 2018-05-02 20:12
Closing due to inactivity.

**Closed by madisonb** 2018-05-02 20:12 UTC
