### ISSUE TITLE
How to solve this?Tried to stop a LoopingCall that was not running.

### ISSUE THREAD

**Issue by keimhaqi** [istresearch/scrapy-cluster#79] opened 2016-10-09 08:35 UTC
Can someone help me?When I ran the example link_spider.py, I got some error like this:

Unhandled error in Deferred:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/scrapy/commands/runspider.py", line 87, in run
    self.crawler_process.crawl(spidercls, **opts.spargs)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/crawler.py", line 163, in crawl
    return self._crawl(crawler, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/crawler.py", line 167, in _crawl
    d = crawler.crawl(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1274, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/crawler.py", line 87, in crawl
    yield self.engine.close()
  File "/usr/local/lib/python2.7/dist-packages/scrapy/core/engine.py", line 100, in close
    return self._close_all_spiders()
  File "/usr/local/lib/python2.7/dist-packages/scrapy/core/engine.py", line 340, in _close_all_spiders
    dfds = [self.close_spider(s, reason='shutdown') for s in self.open_spiders]
  File "/usr/local/lib/python2.7/dist-packages/scrapy/core/engine.py", line 298, in close_spider
    dfd = slot.close()
  File "/usr/local/lib/python2.7/dist-packages/scrapy/core/engine.py", line 44, in close
    self._maybe_fire_closing()
  File "/usr/local/lib/python2.7/dist-packages/scrapy/core/engine.py", line 51, in _maybe_fire_closing
    self.heartbeat.stop()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 202, in stop
    assert self.running, ("Tried to stop a LoopingCall that was "
exceptions.AssertionError: Tried to stop a LoopingCall that was not running.

How can I solve this problem?

**Comment by madisonb** [comment] 2016-10-09 14:26
Can you please post

* the version of Scrapy you are using
* the command that generates this error
* the branch or commit you are running from

So I can try to reproduce it.

**Comment by keimhaqi** [comment] 2016-10-10 00:50
Hi,

- the version of Scrapy I'm using is 1.2.0;
- the command that generates this error is below:
      1. scrapy runspider crawling/spiders/link_spider.py
- the branch I'm running is dev;

before I ran the command "scrapy runspider crawling/spiders/link_spider.py", other kind of stuff I did is below:
- used the kafka_2.10-0.10.0.1 to create a single-node ZooKeeper instance;
- started the Kafka server;
- created a topic "demo.incoming";
- started redis-server;
- ran the command "python kafka_monitor.py";
- ran the command "python redis_monitor.py";

thanks;

**Comment by madisonb** [comment] 2016-10-10 01:21
This project currently supports Scrapy `1.1.2` which is in the `requirements.txt` file. Scrapy 1.2 was just released a week ago and I have not had the time to update the project to run against version 1.2. If you can please downgrade or do `pip install -r requirements.txt` and update this ticket with your results from your environment, that would be great.

If the problem persists I will look into it, but I would first ensure you are using the Scrapy version currently supported.

**Comment by keimhaqi** [comment] 2016-10-10 01:31
Hi,

I just tried Scrapy 1.1.2 and still got same error. Actually I have tried many versions of Scrapy and all of them failed.

thanks

**Comment by madisonb** [comment] 2016-10-10 01:55
What does `./run_offline_tests.sh` produce? Here is what I just did:
```
$ git clone git@github.com:istresearch/scrapy-cluster.git
$ cd scrapy-cluster
$ git checkout dev
$ pip install -r requirements.txt
# on dev branch, need newer scutils
$ pip uninstall scutils
$ cd utils; python setup.py install; cd ../
$ ./run_offline_tests.sh
# all tests pass
```
Can you verify all the offline tests pass? If they do, can you replicate the problem on the `vagrant` machine (follow [this](http://scrapy-cluster.readthedocs.io/en/dev/topics/introduction/quickstart.html#vagrant-quickstart) guide)? I am trying to narrow down what seems to be the issue.

**Comment by keimhaqi** [comment] 2016-10-10 02:20
Hi,

It works well now, I found that the error I got was because I installed scutils in a wrong way, it needs to uninstall scutils-1.1.0 before installing scutils(1.2.0.dev4).

Thank you. ^_^

**Comment by madisonb** [comment] 2016-10-10 02:28
I am glad that solved your issue! The stack trace originally posted is an odd one but I am happy this has been resolved. 

Closing.

**Closed by madisonb** 2016-10-10 02:28 UTC
