### ISSUE TITLE
TypeError: can't pickle thread.lock objects

### ISSUE THREAD

**Issue by wenxzhen** [istresearch/scrapy-cluster#117] opened 2017-04-25 11:21 UTC
Any idea on the issue below:

> Traceback (most recent call last):
>   File "/root/wenxzhen/python27_env/lib/python2.7/site-packages/Twisted-17.1.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 1301, in _inlineCallbacks
>     result = g.send(result)
>   File "/root/wenxzhen/python27_env/lib/python2.7/site-packages/Scrapy-1.3.3-py2.7.egg/scrapy/core/downloader/middleware.py", line 66, in process_exception
>     spider=spider)
>   File "/root/wenxzhen/scrapy-cluster/crawler/crawling/log_retry_middleware.py", line 89, in process_exception
>     self._log_retry(request, exception, spider)
>   File "/root/wenxzhen/scrapy-cluster/crawler/crawling/log_retry_middleware.py", line 103, in _log_retry
>     self.logger.error('Scraper Retry', extra=extras)
>   File "/root/wenxzhen/python27_env/lib/python2.7/site-packages/scutils/log_factory.py", line 244, in error
>     extras = self.add_extras(extra, "ERROR")
>   File "/root/wenxzhen/python27_env/lib/python2.7/site-packages/scutils/log_factory.py", line 319, in add_extras
>     my_copy = copy.deepcopy(dict)
>   File "/root/wenxzhen/python27/lib/python2.7/copy.py", line 163, in deepcopy
>     y = copier(x, memo)
>   File "/root/wenxzhen/python27/lib/python2.7/copy.py", line 257, in _deepcopy_dict
>     y[deepcopy(key, memo)] = deepcopy(value, memo)
>   File "/root/wenxzhen/python27/lib/python2.7/copy.py", line 190, in deepcopy
>     y = _reconstruct(x, rv, 1, memo)
>   File "/root/wenxzhen/python27/lib/python2.7/copy.py", line 334, in _reconstruct
>     state = deepcopy(state, memo)
>   File "/root/wenxzhen/python27/lib/python2.7/copy.py", line 163, in deepcopy
>     y = copier(x, memo)
>   File "/root/wenxzhen/python27/lib/python2.7/copy.py", line 257, in _deepcopy_dict
>     y[deepcopy(key, memo)] = deepcopy(value, memo)
>   File "/root/wenxzhen/python27/lib/python2.7/copy.py", line 163, in deepcopy
>     y = copier(x, memo)
>   File "/root/wenxzhen/python27/lib/python2.7/copy.py", line 264, in _deepcopy_method
>     return type(x)(x.im_func, deepcopy(x.im_self, memo), x.im_class)
>   File "/root/wenxzhen/python27/lib/python2.7/copy.py", line 190, in deepcopy
>     y = _reconstruct(x, rv, 1, memo)
>   File "/root/wenxzhen/python27/lib/python2.7/copy.py", line 334, in _reconstruct
>     state = deepcopy(state, memo)
>   File "/root/wenxzhen/python27/lib/python2.7/copy.py", line 163, in deepcopy
>     y = copier(x, memo)
>   File "/root/wenxzhen/python27/lib/python2.7/copy.py", line 257, in _deepcopy_dict
>     y[deepcopy(key, memo)] = deepcopy(value, memo)
>   File "/root/wenxzhen/python27/lib/python2.7/copy.py", line 190, in deepcopy
>     y = _reconstruct(x, rv, 1, memo)
>   File "/root/wenxzhen/python27/lib/python2.7/copy.py", line 334, in _reconstruct
>     state = deepcopy(state, memo)
>   File "/root/wenxzhen/python27/lib/python2.7/copy.py", line 163, in deepcopy
>     y = copier(x, memo)
>   File "/root/wenxzhen/python27/lib/python2.7/copy.py", line 257, in _deepcopy_dict
>     y[deepcopy(key, memo)] = deepcopy(value, memo)
>   File "/root/wenxzhen/python27/lib/python2.7/copy.py", line 190, in deepcopy
>     y = _reconstruct(x, rv, 1, memo)
>   File "/root/wenxzhen/python27/lib/python2.7/copy.py", line 334, in _reconstruct
>     state = deepcopy(state, memo)
>   File "/root/wenxzhen/python27/lib/python2.7/copy.py", line 163, in deepcopy
>     y = copier(x, memo)
>   File "/root/wenxzhen/python27/lib/python2.7/copy.py", line 257, in _deepcopy_dict
>     y[deepcopy(key, memo)] = deepcopy(value, memo)
>   File "/root/wenxzhen/python27/lib/python2.7/copy.py", line 190, in deepcopy
>     y = _reconstruct(x, rv, 1, memo)
>   File "/root/wenxzhen/python27/lib/python2.7/copy.py", line 334, in _reconstruct
>     state = deepcopy(state, memo)
>   File "/root/wenxzhen/python27/lib/python2.7/copy.py", line 163, in deepcopy
>     y = copier(x, memo)
>   File "/root/wenxzhen/python27/lib/python2.7/copy.py", line 257, in _deepcopy_dict
>     y[deepcopy(key, memo)] = deepcopy(value, memo)
>   File "/root/wenxzhen/python27/lib/python2.7/copy.py", line 163, in deepcopy
>     y = copier(x, memo)
>   File "/root/wenxzhen/python27/lib/python2.7/copy.py", line 230, in _deepcopy_list
>     y.append(deepcopy(a, memo))
>   File "/root/wenxzhen/python27/lib/python2.7/copy.py", line 190, in deepcopy
>     y = _reconstruct(x, rv, 1, memo)
>   File "/root/wenxzhen/python27/lib/python2.7/copy.py", line 334, in _reconstruct
>     state = deepcopy(state, memo)
>   File "/root/wenxzhen/python27/lib/python2.7/copy.py", line 163, in deepcopy
>     y = copier(x, memo)
>   File "/root/wenxzhen/python27/lib/python2.7/copy.py", line 257, in _deepcopy_dict
>     y[deepcopy(key, memo)] = deepcopy(value, memo)
>   File "/root/wenxzhen/python27/lib/python2.7/copy.py", line 190, in deepcopy
>     y = _reconstruct(x, rv, 1, memo)
>   File "/root/wenxzhen/python27/lib/python2.7/copy.py", line 334, in _reconstruct
>     state = deepcopy(state, memo)
>   File "/root/wenxzhen/python27/lib/python2.7/copy.py", line 163, in deepcopy
>     y = copier(x, memo)
>   File "/root/wenxzhen/python27/lib/python2.7/copy.py", line 257, in _deepcopy_dict
>     y[deepcopy(key, memo)] = deepcopy(value, memo)
>   File "/root/wenxzhen/python27/lib/python2.7/copy.py", line 182, in deepcopy
>     rv = reductor(2)
> TypeError: can't pickle thread.lock objects
> 

Thanks,

**Comment by madisonb** [comment] 2017-04-25 14:49
Can you please provide more information on how I can reproduce this error? There shouldn't be a Thread.lock object inside of the extras dict, and I can't reproduce this scraping a site that throws a 504 error.

**Comment by wenxzhen** [comment] 2017-04-26 03:09
thanks to @madisonb 
Will update the issue here if I can reproduce it

**Comment by madisonb** [comment] 2017-05-23 16:35
Please open a new issue if you can give the steps to reproduce this error. Closing.

**Closed by madisonb** 2017-05-23 16:35 UTC
