### ISSUE TITLE
Does anybody get 'Connection pool is full' error when start the docker-compose?

### ISSUE THREAD

**Issue by qianlifu12345** [istresearch/scrapy-cluster#139] opened 2017-10-26 02:25 UTC
Does anybody get *Connection pool is full* error when start the docker-compose?

```shell
~/scrapy-cluster# dockerup
Creating scrapycluster_zookeeper_1
Creating scrapycluster_redis_1
Creating scrapycluster_kafka_1
Creating scrapycluster_kafka_monitor_1
Creating scrapycluster_rest_1
Creating scrapycluster_crawler_1
Creating scrapycluster_redis_monitor_1
WARNING: Connection pool is full, discarding connection: localhost
WARNING: Connection pool is full, discarding connection: localhost
            Name                           Command               State                     Ports
-------------------------------------------------------------------------------------------------------------------
scrapycluster_crawler_1         scrapy runspider crawling/ ...   Up
scrapycluster_kafka_1           start-kafka.sh                   Up      0.0.0.0:9092->9092/tcp
scrapycluster_kafka_monitor_1   python kafka_monitor.py run      Up
scrapycluster_redis_1           docker-entrypoint.sh redis ...   Up      0.0.0.0:32774->6379/tcp
scrapycluster_redis_monitor_1   python redis_monitor.py          Up
scrapycluster_rest_1            python rest_service.py           Up      0.0.0.0:5343->5343/tcp
scrapycluster_zookeeper_1       /docker-entrypoint.sh zkSe ...   Up      0.0.0.0:2181->2181/tcp, 2888/tcp, 3888/tcp

~/scrapy-cluster# netstat -tln
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN
tcp6       0      0 :::2181                 :::*                    LISTEN
tcp6       0      0 :::32774                :::*                    LISTEN
tcp6       0      0 :::5343                 :::*                    LISTEN
tcp6       0      0 :::9092                 :::*                    LISTEN
```

**Comment by madisonb** [comment] 2017-10-26 20:52
If you could specify the os, environment, or ways to reproduce the issue, that would be the most help here. Do you have a lot of docker containers running on the host?

**Comment by madisonb** [comment] 2017-11-02 14:59
I am going to close this ticket tomorrow if I don't hear anything. Unable to reproduce and seems to be an environment specific issue not related to scrapy cluster.

**Closed** 2017-11-03 16:03 UTC
